### ISSUE TITLE
Default facts uses concat_basedir

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/pdk-templates#122]
Default facts uses concat_basedir which is a deprecated fact as part of the concat module.  Also it uses a linux only path.

Why is this included in the default facts for all modules created by the PDK?

**Comment by TheMeier** [comment]
Where does it say that concat_basedir is deprecated?  Actually in the concat module itself its is set as default fact for testing: https://github.com/puppetlabs/puppetlabs-concat/blob/3a2a64343d196fd487e62c1a1ac3716f44c6dc04/spec/default_facts.yml#L5

Without setting it  spec tests which use concat fail.

**Comment by glennsarti** [comment]
The concat_basedir fact was coming from https://github.com/puppetlabs/puppetlabs-concat/blob/1.2.5/lib/facter/concat_basedir.rb .  It was deleted and never replaced, over three years ago, in https://github.com/puppetlabs/puppetlabs-concat/commit/51bd49fcc3773a8268e192c4c02d6a56418e4bce 

> Actually in the concat module itself its is set as default fact for testing

Yes, because this is a PDKified module and it came from this PDK template

> Without setting it spec tests which use concat fail.

Then it should be added, not in the PDK template by default.  It should not be the default for every single module that uses the default PDK template.  And even if it should, it should not be a linux path.  As this could break Windows users of the PDK.
