### ISSUE TITLE
Unable to add additional installation steps into travis configuration

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/pdk-templates#133]
I need to add extra commands before I run tests, e.g. in Travis I need to install PowerShell before spec testing.

I added these in the modsync_configs previously;

https://github.com/puppetlabs/modulesync_configs/commit/c9090578afff58962d5dc99e0bee99259510f5a6

**Comment by Iristyle** [comment]
Hey @bmjen / @scotje is this something that we can address at some point soon?

Thanks!

**Comment by glennsarti** [comment]
Reminder @puppetlabs/pdk This is still outstanding.
