### ISSUE TITLE
NameError: uninitialized constant Bundler

### ISSUE THREAD

**Issue by GoDllkE** [puppetlabs/pdk-templates#139]
After updating the template, I got this error when running `pdk build`:
```
pdk (ERROR): The spec_clean rake task failed with the following error(s):

Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring hitimes-1.2.6 because its extensions are not built. Try: gem pristine hitimes --version 1.2.6
Ignoring nokogiri-1.8.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.2
Ignoring rainbow-2.2.2 because its extensions are not built. Try: gem pristine rainbow --version 2.2.2
Ignoring unf_ext-0.0.7.5 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.5
WARN: Unresolved specs during Gem::Specification.reset:
      puppet-lint (~> 2.0)
      public_suffix (< 4.0, >= 2.0.2)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring hitimes-1.2.6 because its extensions are not built. Try: gem pristine hitimes --version 1.2.6
Ignoring nokogiri-1.8.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.2
Ignoring rainbow-2.2.2 because its extensions are not built. Try: gem pristine rainbow --version 2.2.2
Ignoring unf_ext-0.0.7.5 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.5
rake aborted!
NameError: uninitialized constant Bundler
/home/developer/Documents/Stash/Puppet/profile_linux/Rakefile:3:in `<top (required)>'
/opt/puppetlabs/pdk/share/cache/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

pdk (FATAL): Failed to clean up after running unit tests
```

After some seaching, setting `require 'bundler'` at the top of Rakefile solved the problem. But now comes the question, is this a issue (many more with this problem)? or just a error from my machine environment?

**Comment by rodjek** [comment]
Hi @GoDllkE, I'm sorry that it took so long to get back to you on this. Are you still experiencing this issue? If so, could you please send us some more details on your setup (PDK version, OS, etc)?

**Comment by robertsmieja** [comment]
I'm experiencing the same issue, with the same solution, with a brand new module and fresh Ruby install from rbenv.

I'm on RHEL 6, PDK 1.10.0, ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux].

**Comment by rodjek** [comment]
@robertsmieja are you running PDK from an RPM install? Also, what command are you running when you see that?

**Comment by robertsmieja** [comment]
I am running a PDK from an RPM installed. Output of `yum list installed | grep pdk` :
`pdk.x86_64                           1.10.0.0-1.el6       @puppetlabs-pc1`

I was running `rake` when I saw that error.

**Comment by jacobisaliveandwell** [comment]
I am affected by this issue too. Any updates?

**Comment by mpepping** [comment]
Same issue here on a fresh ruby 2.6.4 from rbenv and pdk 1.13.0. 
Setting require 'bundler' at the top of Rakefile solved the issue though.

**Comment by maxadamo** [comment]
same issue here, since I started installed pdk from rvm and pdk 1.14.0

**Comment by DavidS** [comment]
I've put up a quick PR with the suggested solution. I don't see anything wrong with adding the `require`.

To the underlying question of why this is happening, none of y'all here provided enough detail (e.g. what actual command you were running) to make a analysis. Closest is mpepping who indicates he's using rbenv, which is not necessary when using the pdk RPM.
