### ISSUE TITLE
GetText/DecorateString warning

### ISSUE THREAD

**Issue by Thomas-Franklin** [puppetlabs/pdk-templates#150]
```
Running RuboCop...
Warning: unrecognized cop GetText/DecorateString found in /Users/thomas.franklin/puppet/puppetlabs-panos/.rubocop.yml
Inspecting 85 files
```

**Comment by scotje** [comment]
That cop is provided by the `rubocop-i18n` gem which should be included in the bundle of PDK-managed modules. How are you invoking rubocop?

**Comment by Thomas-Franklin** [comment]
@scotje I use `bundle exec rake rubocop` on a module that has recently been PDK updated. Is it better to be using `pdk validate` instead?

**Comment by scotje** [comment]
@Thomas-Franklin Yes, just running `bundle exec` won't necessarily give you access to all the cached gems that in included in PDK. If you want to only run the rubocop checks you can do `pdk validate ruby`

**Comment by Thomas-Franklin** [comment]
@scotje thank you for the explanation, I shall close this then as it is a non-issue. 👍

**Comment by scotje** [comment]
No problem! Please let us know if you have any other questions or issues!

**Comment by bjvrielink** [comment]
The various CI configs bundled with PDK (Travis, Gitlab CI) do not call pdk, but use bundle exec instead, so this warning is not easily worked around by telling users to only use pdk validate. Please do include a require: rubocop-i18n in the .rubocop.yml, so this warning also disappears in the various pipelines.

**Comment by scotje** [comment]
Ah, yes that's a good point! I think it also may be the case that `pdk validate` is still causing this warning, it just gets captured and ignored. I'll make a PR to update the templated rubocop config.
