### ISSUE TITLE
Cannot sync `puppet-lint --code_on_top_scope` option in PDK 1.9

### ISSUE THREAD

**Issue by krajewf** [puppetlabs/pdk-templates#183]
`code_on_top_scope`check is disabled by default in `puppet-lint`
`.puppet-lint.rc.erb` only disables checks, so it does not appear possible to keep `.puppet-lint.rc` in sync with PDK 1.9 using `.sync.yaml` and `pdk update` if you want to add the  `--code_on_top_scope-check` option

**Comment by DavidS** [comment]
This was implemented in https://github.com/puppetlabs/pdk-templates/pull/181
