### ISSUE TITLE
Missing functional testing

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#194]
We should be able to functionality test that with given data inputs that the templates create expected outputs. This would also give the ability to run validations and linting against the templates.

**Comment by bmjen** [comment]
Can you elaborate on the workflow you're suggesting here?

**Comment by DavidS** [comment]
The basics for this has been implemented in https://github.com/puppetlabs/pdk-templates/pull/90 and the changes following that.
