### ISSUE TITLE
Testing should use the right version of ruby for the latest puppet 6 release

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#203]
Puppet 6 uses ruby 2.5.3

https://puppet.com/docs/puppet/6.3/about_agent.html

**Comment by DavidS** [comment]
If you need (almost) bit-accurate ruby-versions, please use the binaries provided by the PDK packages. Also this has been fixed in your PR and later amended to remain up-to-date with later releases.
