### ISSUE TITLE
Hiera should not default to using common

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#205]
common makes sense for a control repo, not for module data. The 'common' value is the default value specified by the class parameter.

**Comment by binford2k** [comment]
Counterpoint: that means that the parameter will default to a value coming from two different sources of truth. I'd have to look at Hiera and validate that no value is returned, and then look at the class declaration to see if there was a default specified. By setting the 'common' value in `common.yaml` and declaring no default in the class signature, I've only got to look at one source of truth.

**Comment by ghoneycutt** [comment]
Ben, I'd like to agree but the tooling is not there and neither is the community. The pattern is not widely used in the community. If you do not specify a default value, puppet-strings will remove the default value from the REFERENCE.md which makes the module harder to understand. If you look at the code it would seem that the parameter must be specified because it has no value.

**Comment by ghoneycutt** [comment]
If you take a look at PR #206 this is more inline with what most modules need, which is the ability to specify different data per osfamily and major release of each osfamily.

**Comment by ghoneycutt** [comment]
@binford2k you there?

**Comment by ghoneycutt** [comment]
@binford2k could you provide an example where a module uses `common.yaml` for data instead of default values for class parameters? Perhaps I'm misunderstanding you.

**Comment by alexjfisher** [comment]
eg https://github.com/puppetlabs/puppetlabs-ntp/blob/master/data/common.yaml ?

(I'm not necessarily saying I like this pattern.  I also find the puppet-strings limitation a big negative)

**Comment by rtib** [comment]
I don't like having parameter defaults in hiera either, especially within modules. As the PR is touching the initial hiera.yaml only, it won't affect any modules being updated, but forces module developers to think before dumping lots of default values blindfold into common.yaml, only because it's there.

**Comment by ghoneycutt** [comment]
@rodjek wrt the comments above, could you please merge my PR #206. If Puppet feels strongly regarding `common.yaml` they just can add it back at the end. Having platform support in Hiera is super basic for any module.

**Comment by rodjek** [comment]
@ghoneycutt to keep everyone happy can you modify your PR to reintroduce `common.yaml` at the lowest level of the hierarchy?

**Comment by LongLiveCHIEF** [comment]
This is anti-pattern, and is a classic [Principle of Least Priviledge](https://en.wikipedia.org/wiki/Principle_of_least_privilege) problem. Puppet class parameters are the last value in the resolution hierarchy, and therefore the first place to define something. Each additional layer you add data to introduces more complexity to the resolution of that data.

Even _if_ a value presents itself in `common.yaml`, there's no guarantee that is the value that's going to be resolved. While the same holds true for the class parameter default, you know what steps to take if you don't get the value expected in testing.

Putting all the data into hiera introduces a much larger code surface, and exposes that data to a much larger pool of potential side-effects.

Putting all the data into Hiera pollutes its purpose. When you only put the data that's absolutely needed into hiera, it's easy to look at at a glance and know what the most privileged data is.  However, when you put _all_ the data into hiera, you no longer know at a glance which pieces of data should be looked for in a deeper hierarchy within the hiera data set.

The PoLP is the way of identifying this code-smell. Hiera should be self documenting... and if you put all the data into it, you flood it with redundant documentation, making it harder for users to adopt it.

We should (I believe we already do) enforce class parameter typing, and use that to establish the following set of best practices:

- if `[Optional]` does _not_ appear on a param data type, and there is no default value, then it _has to mean_ that the parameter has different defaults for different conditions that are expressed in the hiera hierarchy
- Any default value that is an "absolute" default (it's the same no matter what), should be provided as default in the class parameter declaration

**Comment by ardrigh** [comment]
I am just going to add my :+1:  for keeping them module `common.yaml` for separation of data and code, that Hiera is intended for.

The puppetlabs/ntp module is a perfect example of how to do this properly, with relevant OS defaults.

The failure of Puppet Strings to handle Hiera is a bug in Puppet Strings.

**Comment by david22swan** [comment]
Closing this issue as it seems to have been left open for a significant period of time and the common consensus seems to be against it.
