### ISSUE TITLE
How do you specify a git branch with the template URL ?

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#207]
I'm doing development on this repo and would like to test my branches before sending a pull requests. Tried changing the `template-url` key in the metadata.json of a test module and not having any luck.

snippet from `metadata.json`
```json
  "template-url": "https://github.com/ghoneycutt/pdk-templates#gh205_hiera_defaults",
```

Is there a way to do this? If not, how else are people testing their changes to pdk-templates?

**Comment by bmjen** [comment]
The functionality to specify template-ref will be coming soon.

**Comment by scotje** [comment]
`pdk convert` and `pdk update` both now support a `--template-ref` option.
