### ISSUE TITLE
Testing should use the right version of ruby for the latest puppet 5 release

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#215]
Similar to #203 

Latest puppet 5 release (5.5.10) uses ruby 2.4.5

https://puppet.com/docs/puppet/5.5/about_agent.html

**Comment by DavidS** [comment]
If you need (almost) bit-accurate ruby-versions, please use the binaries provided by the PDK packages. Between that and puppet 5 being EOL by the end of month, I'm gonna close this.
