### ISSUE TITLE
Document how to test changes so the community can contribute

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#220]
How are users supposed to test changes to this repository? What is the work flow that you use?

If you can explain it, I'll document it.

References #217

**Comment by scotje** [comment]
So until super recently this process kind of sucked which hurt the velocity of reviewing PRs on this repo.

But just yesterday we finally merged the big `--template-ref` PR on puppetlabs/pdk so you can now do something like this, which we will work on documenting more formally:

(Running PDK from source, until `--template-ref` goes out in the next release.)

1. Make a module using `master` of the default template: `pdk new module templatetest --skip-interview --template-url=https://github.com/puppetlabs/pdk-templates --template-ref=master`
1. `cd templatetest`
1. `pdk convert --template-url=<URL TO YOUR FORK> --template-ref=<BRANCH NAME OF CHANGE ON YOUR FORK>` and answer "n"
1. Review `convert_report.txt` to see if changes applied as you expected.

Sprinkle in new keys/values in `.sync.yml` as needed to exercise your template change.

Now that we have this change, we will likely be adding some form of CI to this repo that does a version of the above and runs some basic PDK smoke tests against an updated module.

**Comment by ghoneycutt** [comment]
Thanks!

We definitely need a way to do local testing, so you can make local changes to pdk-templates and see how that plays out with a test module. Having to continually commit/force push to your fork is not a great experience.

**Comment by scotje** [comment]
You should be able to do that locally too, `--template-url` will accept a local filesystem to a git workdir.

**Comment by scotje** [comment]
For example:

```
pdk convert --template-url=file:///Users/jesse/src/sdk/pdk-templates --template-ref=gh203_use_correct_ruby_version_for_puppet6
```

And the resulting `convert_report.txt`:

```diff
/* Report generated by PDK at 2019-03-22 13:59:51 -0700 */


--- metadata.json	2019-03-22 13:58:48.988741098 -0700
+++ metadata.json.pdknew	2019-03-22 13:59:51.568249000 -0700
@@ -41,7 +41,7 @@
     }
   ],
   "pdk-version": "1.10.0.pre (heads/master-0-g18721c4)",
-  "template-url": "https://github.com/puppetlabs/pdk-templates#master",
-  "template-ref": "heads/master-0-g373b5dc"
+  "template-url": "file:///Users/jesse/src/sdk/pdk-templates#gh203_use_correct_ruby_version_for_puppet6",
+  "template-ref": "heads/gh203_use_correct_ruby_version_for_puppet6-0-g5ad2d26"
 }


--- .gitlab-ci.yml	2019-03-22 13:58:48.989055971 -0700
+++ .gitlab-ci.yml.pdknew	2019-03-22 13:59:51.569442000 -0700
@@ -15,27 +15,27 @@
   - bundle -v
   - bundle install --without system_tests --path vendor/bundle --jobs $(nproc)
 
-syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop-Ruby 2.5.1-Puppet ~> 6.0:
+syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop-Ruby 2.5.3-Puppet ~> 6:
   stage: syntax
-  image: ruby:2.5.1
+  image: ruby:2.5.3
   script:
     - bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
   variables:
-    PUPPET_GEM_VERSION: '~> 6.0'
+    PUPPET_GEM_VERSION: '~> 6'
 
-parallel_spec-Ruby 2.5.1-Puppet ~> 6.0:
+parallel_spec-Ruby 2.5.3-Puppet ~> 6:
   stage: unit
-  image: ruby:2.5.1
+  image: ruby:2.5.3
   script:
     - bundle exec rake parallel_spec
   variables:
-    PUPPET_GEM_VERSION: '~> 6.0'
+    PUPPET_GEM_VERSION: '~> 6'
 
-parallel_spec-Ruby 2.4.5-Puppet ~> 5.0:
+parallel_spec-Ruby 2.4.5-Puppet ~> 5:
   stage: unit
   image: ruby:2.4.5
   script:
     - bundle exec rake parallel_spec
   variables:
-    PUPPET_GEM_VERSION: '~> 5.0'
+    PUPPET_GEM_VERSION: '~> 5'


--- .travis.yml	2019-03-22 13:58:48.989321128 -0700
+++ .travis.yml.pdknew	2019-03-22 13:59:51.571557000 -0700
@@ -12,10 +12,10 @@
   - 'bundle exec rake $CHECK'
 bundler_args: --without system_tests
 rvm:
-  - 2.5.1
+  - 2.5.3
 env:
   global:
-    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
+    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6"
 matrix:
   fast_finish: true
   include:
@@ -24,7 +24,7 @@
     -
       env: CHECK=parallel_spec
     -
-      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
+      env: PUPPET_GEM_VERSION="~> 5" CHECK=parallel_spec
       rvm: 2.4.5
 branches:
   only:
```

**Comment by ghoneycutt** [comment]
Thanks @scotje 

This is a pretty confusing way to use `convert` as its perceived usage is to convert a module to use PDK and not use with a module already running PDK.

**Comment by ghoneycutt** [comment]
@scotje I get this

```
convert: illegal option -- template-ref
```

when running

`pdk convert --template-url=file:///Users/gh/git/pdk-templates --template-ref=master`

adding `--debug` does not display any more information

Using PDK 1.9.1

**Comment by scotje** [comment]
This change was just merged, so the `--template-ref` option is only available if you are running from source right now, but we are tentatively planning a release for this week that it will be a part of.

**Comment by scotje** [comment]
Also, I was mistaken that `convert` has to be used for every step. You have to use `convert` to initially change your `--template-url` to point at a new template repo, but after that you can use `pdk update` with `--template-ref` to compare between revisions in the same repo.

**Comment by DavidS** [comment]
Between the changes to the PDK and this repo now having acceptance tests using it to ensure that basic functionality still works, I think we can lay this to rest.
