### ISSUE TITLE
Make .travis.yml's dist attribute configurable

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#221]
There is generally no reason necessary to specify the dist. The dist is currently hard coded to 'trusty' which is already the default used by TravisCI. Anyhow, it should be configurable.

https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system

**Comment by glennsarti** [comment]
> There is generally no reason necessary to specify the dist

100% disagree.  I've had to manually set the distribution because I needed Xenial.

I want this PR merged!!

**Comment by ghoneycutt** [comment]
You may have had to manually set it, though that's not the default case. Anyhow, could we get some movement on the PR ?

**Comment by rtib** [comment]
👍

**Comment by rtib** [comment]
Have tested it successfully with default and non-default settings.
