### ISSUE TITLE
.travis.yml automatically adds deploy section with incorrect user

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#223]
The README does not explain how to specify a deploy user/password. This further compounds the issue that pdk-templates adds the deploy section by default as it is not clear how to override the user and specify a password.

Suggest that the deploy section is not automatically added by removing `deploy: true` from `config_defaults.yml`. The `branches` attribute should be left in there. Documentation is needed to show how to add your username/password along with a link to the TravisCI documentation on how to create and encode the password.

**Comment by rtib** [comment]
I think this can be closed, as it was addressed with PR #224 .

**Comment by rodjek** [comment]
@rtib for sure, thanks for catching it! :)
