### ISSUE TITLE
rubocop complains about default cops

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#227]
```
Warning: unrecognized cop GetText/DecorateString found in /Users/gh/git/puppet-module-rpcbind/.rubocop.yml
```

Using PDK 1.9.1. You can reproduce with

```
pdk bundle exec rake rubocop
```

which is what happens by default with the TravisCI configs

If you ran `pdk validate` you would not see the warning. Even running with `--debug` this information is not displayed. This is a bug from a UX standpoint as you will see warnings in TravisCI and then not be able to reproduce using the standard tooling ala `pdk validate` instead of resorting to `pdk bundle exec`.

**Comment by term1n4l** [comment]
I followed the recommendations here:

https://github.com/puppetlabs/rubocop-i18n

And resolved this issue

**Comment by ghoneycutt** [comment]
This will be an ongoing issue due to the rapid changes of rubocop. We should adopt a policy of disabling all cops by default and then enabling the ones we want instead of the current policy of taking whatever new thing rubocop thinks is a good idea, having it fail builds and likely not add any real value and then disabling it.

**Comment by term1n4l** [comment]
Just thinking out loud here, could this not be accomplished by dashing out cops in .sync.yml?

**Comment by scotje** [comment]
This should have been fixed by https://github.com/puppetlabs/pdk-templates/pull/280 in PDK 1.14.0, please let us know if it is still an issue.
