### ISSUE TITLE
appveyor: enable adding commands before the actual test command

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/pdk-templates#229]
To run commands before the default `bundle exec rake...`, add a `before_test` key to the template that fills in the corresponding section in the appveyor.yml file.

e.g.
`.sync.yml` 
```
appveyor.yml:
  before_test:
  - pwsh -NoProfile -NoLogo -NonInteractive -Command $PSVersionTable
  - powershell -NoProfile -NoLogo -NonInteractive -Command $PSVersionTable
```

generates the following appveyor.yml snippet
```
before_test:
  - pwsh -NoProfile -NoLogo -NonInteractive -Command $PSVersionTable
  - powershell -NoProfile -NoLogo -NonInteractive -Command $PSVersionTable
```

**Comment by DavidS** [comment]
1) Please use the knockout prefix to remove unwanted entries. I understand that this is brittle and unwieldy for this particular problem, but it is the literal answer to the statement in the title.

2) Adding support for a `before_test` configuration would be a quite straight-forward addition to allow folks to add commands before the actual tests are run. When doing so, please make sure to update the README section to mention the new key.

**Comment by DavidS** [comment]
Rewrote the ticket and title to be more positive and forward looking. This looks like a good candidate task for someone who wants to get started with contributing to the PDK templates.

**Comment by jordanbreen28** [comment]
Closing as template is no longer shipped.
