### ISSUE TITLE
Ignore .vscode directory

### ISSUE THREAD

**Issue by rtib** [puppetlabs/pdk-templates#266]
In some cases VSCode is creating the `.vscode` directory within the module root. This should be ignored for git, as it already ignored for pdk.

**Comment by rtib** [comment]
Was added with #202 to `.pdkignore`

**Comment by glennsarti** [comment]
The `.vscode` directory exists for project specific settings.  It's supposed to checked into source control normally. But not part of the module build process.

**Comment by rtib** [comment]
Correct, it belongs to a very specific IDE, not the module itself. For sharing and versioning project specific IDE settings, git submodules would be feasible.

**Comment by scotje** [comment]
Hi @rtib, to clarify a bit, we would eventually like to make things like the various editor and CI config files more opt-in, but the way things are right now, we don't think it's the right choice for everyone to have `.vscode` be ignored by default.

**Comment by rtib** [comment]
To me, It's completely ok. My opinion on that topic seems to be a bit different, or maybe aged? Editors and IDE come and go with time: remember Geppetto, various Eclipse and Netbeans plug-ins, RubyMine, puppet-vim, Atom, etc? VSCode is currently very popular, I'am also using it, but I don't know which hype comes next month. Therefore, I still don't want any kind of editor lock-in within particular projects. These should be free of such elements to not lock any contributor to any development environment.

As the per-project opt-out is working, that's fine to me.

**Comment by scotje** [comment]
Yep, the goal is to eventually make editor and CI configs (and maybe other things) additional "features" that you can layer on top of the default template.
