### ISSUE TITLE
Document 'required' parameter of .gitignore/.pdkignore configuration in .sync.yml

### ISSUE THREAD

**Issue by jay7x** [puppetlabs/pdk-templates#292]
## Describe the Change You Would Like
I was looking a way to remove one of predefined lines from .gitignore using knockout prefix. But as only 'paths' parameter is documented I was trying to put that prefixed line into it. Though there is undocumented 'required' parameter which actually did the thing. Could you please document 'required' as well?

**Comment by DavidS** [comment]
see example at https://github.com/puppetlabs/puppetlabs-service/blob/d9bff37f3f709d7b56acde020464119d9460aae4/.sync.yml#L2-L4
