### ISSUE TITLE
Should Gemfile's 'optional' key create optional groups?

### ISSUE THREAD

**Issue by jay7x** [puppetlabs/pdk-templates#294]
## Describe the Bug
If I understand docs right, Gemfile's `optional` key is for creating optional groups in Gemfile (e.g. I can have group of gems in my Gemfile which are used by core developers but not by the rest of the team:
```
group :hardcore, optional: true do
...
end
```
I'm expecting this group to be optional, so it will not be installed by `pdk bundle install` by default.

So if my understanding is correct, `optional` key should mark group as `optional: true`. But I don't see anything related in Gemfile.erb template.

If I misunderstand it then please close this issue (and update docs maybe).

**Comment by david22swan** [comment]
Hey, thank you for brining this to our attention, however as part of the process of cleaning up our older issues and getting on top of our backlog, we our now closing out older issues that have not been active within the last few years.
If you feel that this is still a significant issue please feel free to reopen this and ping us directly.
