### ISSUE TITLE
Add hiera validation to CI definitions.

### ISSUE THREAD

**Issue by JacobHenner** [puppetlabs/pdk-templates#30]
To compliment https://github.com/puppetlabs/pdk/issues/246 and https://github.com/puppetlabs/pdk/issues/424, the default pdk template should include steps in each CI definition for validating/linting module-scoped hiera data. yaml should definitely be supported, and perhaps json too?

**Comment by DavidS** [comment]
This is being tracked in https://tickets.puppetlabs.com/browse/PDK-742

**Comment by scotje** [comment]
This issue was moved to puppetlabs/pdk-planning#24
