### ISSUE TITLE
Is it time to upgrade default ruby version in templates?

### ISSUE THREAD

**Issue by Felixoid** [puppetlabs/pdk-templates#304]
## Use Case
The puppet version 4 is far away from the end of life. Maybe, it's proper time to adjust templates to version 5 2.4.5?

## Describe the Solution You Would Like
Add magic comment `# frozen_string_literal: true` to every rb template, update default target version in rubocop and so on

## Describe Alternatives You've Considered
Or it can stay as it is

**Comment by Felixoid** [comment]
I can prepare some PR to start if it's a discussable topic.

**Comment by kenyon** [comment]
#306 should have closed this.
