### ISSUE TITLE
The litmus provision_list and puppet_collection arrays can't be replaced, just added to.

### ISSUE THREAD

**Issue by natemccurdy** [puppetlabs/pdk-templates#317]
## Describe the Bug
When using the new `use_litmus` boolean (added in #296), setting custom values for `provision_list` and `puppet_collection` should REPLACE the default values. What actually happens is that your custom  values get ADDED TO the defaults.

For example, if I want to provision just the `centos` target with Puppet 6, I was hoping I could set this in .sync.yaml:
```
.travis.yml:
  use_litmus: true
  litmus:
    provision_list: [centos]
    puppet_collection: [puppet6]
```

But instead the `provision_list` array gets added to [the defaults](https://github.com/puppetlabs/pdk-templates/blob/1.16.0/config_defaults.yml#L89
) resulting in an array like `['travis_deb', 'travis_el', 'centos']`.

And it's all duplicated for puppet5 even though I specified just puppet6.

## Expected Behavior
Setting `provision_list: [centos]` results in a .travis.yaml with JUST the `centos` targets and not the `travis_deb` and `travis_el` targets.

Setting `puppet_collection: [puppet6]` results in a .travis.yaml with JUST the puppet6 target and not the puppet5 and puppet6 targets.

**Comment by scotje** [comment]
Switching this over to an "enhancement" as this is (for better or worse) how arrays have always behaved in `.sync.yml`. We do agree though that what you want to do should be possible so we are going to brainstorm some ways to introduce new patterns for working with array values.

**Comment by DavidS** [comment]
Use the `---` knockout prefix to remove values from arrays and hashes:
```
---
.travis.yml:
  use_litmus: true
  litmus:
    provision_list: [---travis_deb, ---travis_el, centos]
    puppet_collection: [---puppet5, puppet6]

```
![2021-01-18_11MS+0000_836x462](https://user-images.githubusercontent.com/27712/104908969-1bf9b380-597f-11eb-925b-93d57180cf87.png)
