### ISSUE TITLE
Support `documentation` type changelog entries.

### ISSUE THREAD

**Issue by bstopp** [puppetlabs/pdk-templates#325]
## Use Case
I'd like to support a specific section in the Rakefile for changelog generation: `documentation`

## Describe the Solution You Would Like
An update to the Rakefile template that adds a documentation section based on that tag in Github.

(As a side note, is the specific `skywinder` commit still needed? - that commit is in release 1.15.0)

**Comment by DavidS** [comment]
> ## Use Case
> 
> I'd like to support a specific section in the Rakefile for changelog generation: `documentation`
> ## Describe the Solution You Would Like
> 
> An update to the Rakefile template that adds a documentation section based on that tag in Github.

This is already in https://github.com/puppetlabs/pdk-templates/blob/08da147c02a8169c43eecaae9da19ad1bfe26077/moduleroot/Rakefile.erb#L111 - If you want to change this from "Fixed" to a distinct "Documentation" header, please do submit a PR with a sentence or two on rationale.

> (As a side note, is the specific `skywinder` commit still needed? - that commit is in release 1.15.0)
That's been already fixed.
