### ISSUE TITLE
simplecove 0.19.0 requires Ruby version >= 2.5.0

### ISSUE THREAD

**Issue by TheMeier** [puppetlabs/pdk-templates#345]
## Describe the Bug
unit test for puppet 5 failes with gitlab since it uses ruby version 2.4.5
```
Gem::RuntimeRequirementNotMetError: simplecov requires Ruby version >= 2.5.0.
The current ruby version is 2.4.5.335.
An error occurred while installing simplecov (0.19.0), and Bundler cannot
continue.
Make sure that `gem install simplecov -v '0.19.0' --source
'https://rubygems.org/'` succeeds before bundling.
In Gemfile:
  puppet-module-posix-dev-r2.4 was resolved to 0.5.0, which depends on
    codecov was resolved to 0.1.20, which depends on
      simplecov
```
(configured in 
https://github.com/puppetlabs/pdk-templates/blob/master/config_defaults.yml#L618-L621)

Also this test can not be removed because of https://github.com/puppetlabs/pdk-templates/issues/328

## Expected Behavior
Default jobs from default templates should run without failure

## Steps to Reproduce
take any module with unit tests and run them on gitlab-ci with a docker runner.

## Environment
 - GitLab Enterprise Edition 13.2.4-ee 
 - Ruby 2.4.5
 - Puppet ~> 5

**Comment by binford2k** [comment]
https://github.com/simplecov-ruby/simplecov/releases/tag/v0.19.0

**Comment by TheMeier** [comment]
Thanks for the hint @binford2k

**Comment by binford2k** [comment]
Oh, I think we still need to address this in the templates! Was just pointing out the root cause that we'll need to accommodate for.

**Comment by sanfrancrisko** [comment]
We've had a few issues with the testing / releasing of the gem, but it should be expected within the next hour or two. I'll link the associated PR to this issue.
