### ISSUE TITLE
Puppet 7 support

### ISSUE THREAD

**Issue by wmuizelaar** [puppetlabs/pdk-templates#369]
Hi, now that Puppet 7 is released, are there any plans to provide support for puppet7 in all the tests that are created by these pdk templates?

**Comment by DavidS** [comment]
The Content Team has been releasing pdk-templates-based modules with puppet7 support for a while now without issues.

Did you have specific issues with using these templates with puppet7? Feel free to create new tickets on specific issues you encounter!

**Comment by bodgit** [comment]
I think the point was that the `config_defaults.yml` still just specifies Puppet versions 5.x & 6.x with no mention of 7.x.
