### ISSUE TITLE
Useable Github Actions templates

### ISSUE THREAD

**Issue by bodgit** [puppetlabs/pdk-templates#440]
## Use Case
I've been using the Travis CI templates for OSS module testing however it is becoming increasingly apparent that Travis CI is going to be unusable going forward. The ".org" infrastructure was going to be switched off last month but has had a stay of execution until the 15th of June. Internet evidence suggests that the ".com" infrastructure is not viable unless you're willing to pay for it as requests for "OSS credits" are being denied.

Given the module sources are hosted on Github it seems logical to switch to a workflow using Actions instead, however the current PDK templates are noted as being reliant on internal Puppet resources.

## Describe the Solution You Would Like
I would like to see templates for Github Actions that are not reliant on internal Puppet resources and just have comparable functionality to what the Travis CI template has.

**Comment by sanfrancrisko** [comment]
Hi @bodgit, thanks for raising the issue. We'd like to make you aware of the DevX Team's plans for the future of PDK: https://puppet.com/blog/the-future-of-the-puppet-developer-kit-pdk/

Could you raise an idea for this feature in [the discussions of the pdkgo repo](https://github.com/puppetlabs/pdkgo/discussions). 

For more info on what PCT is and to try it out in pre-release form: https://puppetlabs.github.io/iac/pdk/development/2021/06/04/pct-early-release.html
