### ISSUE TITLE
Skip Honeycomb if Disabled

### ISSUE THREAD

**Issue by thebeanogamer** [puppetlabs/pdk-templates#449]
## Describe the Bug

If `common['honeycomb']` is set to false in `.sync.yml`, the environment variables to specify API keys for Honeycomb aren't included but GitHub will still run the action. This causes Honeycomb to crash out and the job to fail. This can be seen [here](https://github.com/ractf/puppet-polaris/runs/3427485564).

## Expected Behavior

PDK should remove references to Honeycomb from the GitHub Actions job if Honeycomb has been disabled in `.sync.yml`.

## Steps to Reproduce

1. Disable `honeycomb` in `.sync.yml`.
  ```yaml
  common:
    honeycomb: false
  ```
2. Run `pdk update` to apply the template.
3. Commit to GitHub and check the output from GitHub Actions.

## Environment
 - Version
   - PDK `2.2.0`
   - PDK templates `51828b4`
 - Platform
   - Fedora 34

## Additional Context

Honeycomb is pretty deeply embedded into the CI jobs, so this could be quite hard to remove.

**Comment by sanfrancrisko** [comment]
Have had a quick look at this, but there's wider impact to other products / processes. This won't be as quick as I thought, but we'll try to provision time to implement this.
