### ISSUE TITLE
Enhance templates to handle rules in .gitlab-ci.yml section of sync.yml

### ISSUE THREAD

**Issue by rgardner4012** [puppetlabs/pdk-templates#472]
## Use Case
Gitlab has added rules to it's jobs as a replacement/enhancement for except/only. Would like to be able to make use of them in templates.

Would like to enable rules mimicking the except/only usage that is currently in use for ruby_versions\{job}\except/only

Only other way I've found to do this is move the entire job over to a custom job.

**Comment by pmcmaw** [comment]
Hey @rgardner4012 as PDK v3.0.0 the gitlab config was removed and therefore I am closing this issue as it is no longer relevant. However I have kicked off a discussion on putting it back if we get a general consensus of what people want. If you are interested please feel free to contribute. https://github.com/puppetlabs/pdk-templates/discussions/562
