### ISSUE TITLE
set/allow interruptible in gitlabci jobs

### ISSUE THREAD

**Issue by juliantaylor** [puppetlabs/pdk-templates#489]
## Use Case
The jobs created are just checks which can be interrupted when the reference being tested is obsolete (e.g. due to new commits
https://docs.gitlab.com/ee/ci/yaml/#interruptible

## Describe the Solution You Would Like
The gitlabci configuration should either set interruptible: true by default or allow setting it (or allow users to set arbitrary configuration to the generated lint jobs for future proofing)

**Comment by david22swan** [comment]
Hey, thank you for brining this to our attention, however as part of the process of cleaning up our older issues and getting on top of our backlog, we are now closing out this issue as the .gitlab-ci.yml.erb has been removed from the templates.
