### ISSUE TITLE
facter_implementation missing quotes

### ISSUE THREAD

**Issue by ardrigh** [puppetlabs/pdk-templates#509]
## Describe the Bug
Details in https://github.com/puppetlabs/pdk/issues/1238

## Expected Behavior
Template would create a valid value

## Steps to Reproduce
Details in https://github.com/puppetlabs/pdk/issues/1238

## Additional Context
Please review the PR I created to fix the error https://github.com/puppetlabs/pdk-templates/pull/508

**Comment by greatflyingsteve** [comment]
As a workaround, until the linked PR gets merged, giving the value in .sync.yml as `facter_implementation: "'rspec'"` will produce the appropriate quoted value.

**Comment by ardrigh** [comment]
PR was merged, closing this issue
