### ISSUE TITLE
Deploy puppetforge user not configurable in travis.yml

### ISSUE THREAD

**Issue by edestecd** [puppetlabs/pdk-templates#51]
https://github.com/puppetlabs/pdk-templates/blob/master/moduleroot/.travis.yml.erb#L76

Its hard coded to puppet :(

**Comment by ardrigh** [comment]
Related PR I put in for this https://github.com/puppetlabs/pdk-templates/pull/32

**Comment by DavidS** [comment]
This has been fixed in #32.
