### ISSUE TITLE
Wrong things added?

### ISSUE THREAD

**Issue by mkoe** [puppetlabs/pdk-templates#525]
## Describe the Bug
If i look at tags 3.2.0 and beyond in this branch, i will get the stuff for 
Class: docker. 
Personally i don't think that this should be like this.

## Expected Behavior
Get the pdk-templates for all tags in this git repository

## Steps to Reproduce
Checkout tag 3.2.0 or beyond in this repository.

**Comment by jordanbreen28** [comment]
Hey @mkoe,
Please use the latest tag, which in this case is 3.0.0.
Any tags greater than this are historic and will need removed, so thanks for pointing them out to us.

**Comment by jordanbreen28** [comment]
@mkoe I'll go ahead and close this, please re-open if necessary.
