### ISSUE TITLE
Should PDK also work with templates on our internal GitHub Enterprise?

### ISSUE THREAD

**Issue by rheijkoop** [puppetlabs/pdk-templates#534]
## Describe the Bug
We use an internal GitHub Enterprise but after copying the pdk-templates to our internal repository I can't run a 

`pdk convert --template-url https://github.****.****.****/team-puppet-modulebouw/pdk_templates`

I get the following error: 
`pdk (FATAL): Unable to find a valid template at https://github.****.****.****/team-puppet-modulebouw/pdk_templates#main`

The main branch does exist

## Expected Behavior
I would like to convert over 100 internal puppet modules and profiles using PDK 3.0.0

## Steps to Reproduce
`pdk convert --template-url https://github.****.****.****/rheijkoop/pdk_templates`

Gives the following error: 
`pdk (FATAL): Unable to find a valid template at https://github.****.****.****/team-puppet-modulebouw/pdk_templates#main`

## Environment
 - Version 3.0.0
 - Platform Windows 11

## Additional Context
I have cloned our module to my laptop and am trying to convert it using PDK 3.0.0
Our local repository for the template is a fork from github.com. I get the same error., with or without any changes to the template.
A convertion using the default Puppet template does work. It also works when I use a fork on github.com. Even with the needed changes to my template (https://github.com/rheijkoop/pdk-templates does work)

**Comment by nabertrand** [comment]
Is that repo publicly available? With our enterprise GitHub setup we have to use key-based authentication to access the template repo, e.g. `--template-url ssh://git@github.****.****.****/rheijkoop/pdk_templates.git`

**Comment by rheijkoop** [comment]
I have tested your solution and can confirm that this works. Thanks!
We now get our own .rubocop.yml and a 100% coverage report in rspec from our internal template.
