### ISSUE TITLE
networking key in default_facts.yml masks all values from rspec-puppet-facts

### ISSUE THREAD

**Issue by silug** [puppetlabs/pdk-templates#543]
## Describe the Bug
Adding a top-level `networking` key in `spec/default_facts.yml` masks all values in the `networking` key from rspec-puppet-facts.  For example, in tests `networking.fqdn` is not defined.

## Expected Behavior
The `networking` facts provided by rspec-puppet-facts should work in tests.

## Steps to Reproduce
1. `pdk new module`
2. Update `template-url` and `template-ref` to point to upstream.
```json
  "template-url": "https://github.com/puppetlabs/pdk-templates#3.0.0",
  "template-ref": "tags/3.0.0-0-g5bfc1c0"
```
3. `pdk update`
4. Create an empty class with `pdk new class` and add the following to the generated spec test:
```ruby
      let(:pre_condition) do
        <<~END
          if $facts['networking']['fqdn'].empty {
            fail("No fqdn fact: networking => ${facts['networking']}")
          }
        END
      end
```
5. `pdk test unit`

The resulting error will look like this:
```
     Failure/Error: it { is_expected.to compile.with_all_deps }
       error during compilation: Evaluation Error: Error while evaluating a Function Call, No fqdn fact: networking => {ip => 172.16.254.254, ip6 => FE80:0000:0000:0000:AAAA:AAAA:AAAA, mac => AA:AA:AA:AA:AA:AA}
```

## Environment
 - Version 3.0.0
 - Platform Fedora 39 (using the Fedora 36 package)

## Additional Context
In previous versions of the templates, only top-level keys were defined in `spec/default_facts.yml`, so the `merge` that was happening in `spec/spec_helper.rb` worked fine with default values.  With nested facts added to `spec/default_facts.yml`, the `merge` needs to be replaced with a `deep_merge`.

Note that simply removing `spec/default_facts.yml` by adding
```yaml
spec/default_facts.yml:
  delete: true
```
to `.sync.yml` and running `pdk update` also works since the default provided facts are being provided by rspec-puppet-facts already.

**Comment by jordanbreen28** [comment]
thanks for raising this @silug.
I've raised https://github.com/puppetlabs/pdk-templates/pull/544, if you get a moment could you update the template ref to that PR branch, run `pdk update` and let me know how that works out?
Thanks again

**Comment by silug** [comment]
@jordanbreen28 That change does not appear to affect the behavior.  I'm guessing the `add_custom_fact` function is where the change needs to happen.  I'm not sure where that's coming from though.

**Comment by silug** [comment]
If it helps, I generated a module with the steps necessary to demonstrate the issue at https://github.com/silug/issue_543.

**Comment by jordanbreen28** [comment]
> @jordanbreen28 That change does not appear to affect the behavior.  I'm guessing the `add_custom_fact` function is where the change needs to happen.  I'm not sure where that's coming from though.

@silug From what I can see, `add_custom_fact` is being pulled in from rspec-puppet-facts.

**Comment by jay7x** [comment]
Just hit that with PDK templates v3.0.1. Can we maybe delete the `default_facts.yml` completely and suggest to use `rspec-puppet-facts` way by default?
