### ISSUE TITLE
Implement allow list for .pmtignore

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/pdk-templates#574]
## Use Case

https://github.com/puppetlabs/puppet-specifications/pull/157 implements an allow list for files in a module release. Usually a .pmtignore file is used to exclude/include files in a release. I don't know if pdk still uses the .pmtignore or anything else. Anyways I think pdk-template should implement such a filter (or maybe pdk? I don't know for sure).

## Describe the Solution You Would Like

Implement a deny list to honour https://github.com/puppetlabs/puppet-specifications/pull/157

**Comment by jordanbreen28** [comment]
I missed this, somehow! Sorry @bastelfreak, I'll close this in favour of the newly opened one!
