### ISSUE TITLE
Not possible to use a custom image from a private registry with .gitlab-ci.yml

### ISSUE THREAD

**Issue by Odiobill** [puppetlabs/pdk-templates#86]
Currently it is not possible to use a custom docker image with _.gitlab-ci.yml_. The template contains:

```
image: ruby:<%= ruby_version %>
```

making it impossible to reference an image from a private docker registry. It would be very handy to include such a feature.

**Comment by Odiobill** [comment]
@cdenneen actually I didn't try that, because I thought that having a proper option would be a better approach. I've asked for a simple pull request for that (https://github.com/puppetlabs/pdk-templates/pull/98) and, meanwhile, I'm using my fork's URL with the --template-url option

**Comment by TheMeier** [comment]
this no longer applies 
fiexd in
 https://github.com/puppetlabs/pdk-templates/commit/ed3e719eae25a4fb54aeb02a8741ce941121124f
and 
https://github.com/puppetlabs/pdk-templates/commit/39a4af0b0dcaad6c58fd568370e87cee74b24f6d

**Comment by kenyon** [comment]
close plz thx
